
module.exports.Heroes = [
  'Abathur',
  'Alarak',
  'Anub\'arak',
  'Artanis',
  'Arthas',
  'Auriel',
  'Azmodan',
  'Brightwing',
  'Cassia',
  'Chen',
  'Cho',
  'Chromie',
  'D.Va',
  'Dehaka',
  'Diablo',
  'E.T.C.',
  'Falstad',
  'Gall',
  'Garrosh',
  'Gazlowe',
  'Genji',
  'Greymane',
  'Gul\'dan',
  'Illidan',
  'Jaina',
  'Johanna',
  'Kael\'thas',
  'Kerrigan',
  'Kharazim',
  'Leoric',
  'Li Li',
  'Li-Ming',
  'Lt. Morales',
  'Lúcio',
  'Lunara',
  'Malfurion',
  'Malthael',
  'Medivh',
  'Muradin',
  'Murky',
  'Nazeebo',
  'Nova',
  'Probius',
  'Ragnaros',
  'Raynor',
  'Rehgar',
  'Rexxar',
  'Samuro',
  'Sgt. Hammer',
  'Sonya',
  'Stitches',
  'Stukov',
  'Sylvanas',
  'Tassadar',
  'The Butcher',
  'The Lost Vikings',
  'Thrall',
  'Tracer',
  'Tychus',
  'Tyrael',
  'Tyrande',
  'Uther',
  'Valeera',
  'Valla',
  'Varian',
  'Xul',
  'Zagara',
  'Zarya',
  'Zeratul',
  'Zul\'jin',
  'Kel\'Thuzad',
  'Ana',
  'Junkrat',
  'Alexstrasza',
  'Hanzo',
  'Blaze',
  'Maiev',
  'Fenix',
  'Deckard',
  'Yrel',
  'Whitemane',
  'Mephisto',
  'Mal\'Ganis',
  'Orphea',
  'Imperius',
  'Anduin',
  'Qhira'
];

module.exports.GameTypes = [
  'Hero League',
  'Storm League',
  'Team League',
  'Unranked Draft',
  'Quick Match'
];

module.exports.Maps = [
  'Battlefield of Eternity',
  'Blackheart\'s Bay',
  'Braxis Holdout',
  'Cursed Hollow',
  'Dragon Shire',
  'Garden of Terror',
  'Hanamura Temple',
  'Haunted Mines',
  'Infernal Shrines',
  'Sky Temple',
  'Tomb of the Spider Queen',
  'Towers of Doom',
  'Warhead Junction',
  'Volskaya Foundry',
  'Alterac Pass',
  'Escape From Braxis',
  'Industrial District',
  'Lost Cavern',
  'Pull Party',
  'Silver City',
  'Braxis Outpost',
  'Checkpoint: Hanamura'
];

module.exports.Regions = {
  1: 'NA',
  2: 'EU',
  3: 'KR',
  5: 'CN'
};

module.exports.HeroesProfileStats = [
  'kills',
  'assists',
  'takedowns',
  'deaths',
  'highest_kill_streak',
  'hero_damage',
  'siege_damage',
  'structure_damage',
  'minion_damage',
  'creep_damage',
  'summon_damage',
  'healing',
  'self_healing',
  'damage_taken',
  'experience_contribution',
  'town_kills',
  'time_spent_dead',
  'merc_camp_captures',
  'watch_tower_captures',
  'meta_experience',
  'protection_allies',
  'silencing_enemies',
  'rooting_enemies',
  'stunning_enemies',
  'clutch_heals',
  'escapes',
  'vengeance',
  'outnumbered_deaths',
  'teamfight_escapes',
  'teamfight_healing',
  'teamfight_damage_taken',
  'teamfight_hero_damage',
  'multikill',
  'physical_damage',
  'spell_damage',
  'regen_globes'
];
